# Default values for oscar.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

  # JAVA_OPTS: {{ .Values.global.env.javaOpts.oscar }}
  # CATALINA_OPTS: {{ .Values.global.env.catalinaOpts }}
  # TZ: {{ .Values.global.env.timezone }}

env:
  catalinaOpts: -Djava.awt.headless=true
  javaOpts: -Dlog4j2.formatMsgNoLookups=true -XX:+UseCMSInitiatingOccupancyOnly -XX:+UseConcMarkSweepGC -Xmx2G -Xms2G -XX:MaxPermSize=1G -XX:CMSInitiatingOccupancyFraction=68 -Xincgc -Dorg.apache.el.parser.COERCE_TO_ZERO=true

replicaCount: 2

image:
  repository: openosp/open-osp
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

imagePullSecrets: []
nameOverride: "oscar"
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

ingress:
  enabled: false
  className: ""
  annotations: {}

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

resources: 
  limits:
    # cpu: 2
    # memory: 15Gi
  # requests:
    # cpu: 1
    # memory: 6Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

persistence: {}

restartPolicy: Always

volumeMounts:
  - name: oscar-config
    mountPath: /root/oscar.properties 
      # subPath: oscar.properties
  - name: drugref2-config
    mountPath: /root/drugref2.properties
      # subPath: drugref2.properties
  - name: bucket-claim
    mountPath: /var/lib/OscarDocument
    subPath: oscar
    #- name: oscar-chain
    # mountPath: /usr/local/tomcat/conf/chain.pem
    # subPath: chain.pem
  - name: ssl-crt
    mountPath: /usr/local/tomcat/conf/ssl.crt
  - name: ssl-key
    mountPath: /usr/local/tomcat/conf/ssl.key
  - name: bucket-claim
    mountPath: /static/css
    subPath: /static/css
  - name: bucket-claim
    mountPath: /static/images
    subPath: static/images

volumes:
  - name: oscar-config
    configMap:
      name: oscar-properties
  - name: drugref2-config
    configMap:
      name: drugref2-properties
  - name: bucket-claim
    persistentVolumeClaim:
      claimName: s3-bucket
  # TODO: TBD
  #  - name: oscar-chain
  #  path: "{{ include \"openosp.localStorageBasePath\" . }}/config/chain.pem"
  - name: ssl-crt
    secret:
      secretName: ssl
      items:
        - key: ssl.crt
          path: ssl.crt
  - name: ssl-key
    secret:
      secretName: ssl
      items:
        - key: ssl.key
          path: ssl.key
