{{- if eq .Values.akv2k8s.enabled true }}
  {{- range .Values.akv2k8s.secrets }}
---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: {{ .objectName }}-akv2k8s
  namespace: {{ $.Release.Name }}
spec:
  vault:
    name: {{ $.Values.akv2k8s.vaultName }}
    object:
      name: {{ .objectName }}
      type: {{ .type | default "secret" | quote }}
      {{- if eq .type "multi-key-value-secret" }}
      contentType: application/x-{{ .contentType }}
      {{- end }}
  {{- if eq .sync true }}
  output:
    secret:
      name: {{ .outputName }}
      {{- if ne .type "certificate" }}
      dataKey: {{ .data }} 
      {{- else }}
      type: {{ .data }}
      {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
