apiVersion: v1
kind: Service
metadata:
  name: {{ include "mariadb.name" . }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
spec:
  clusterIP: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.global.services.db.port }}
      targetPort: {{ .Values.global.services.db.port}}
      protocol: TCP
  selector:
    {{- include "mariadb.selectorLabels" . | nindent 4 }}
