apiVersion: v1
kind: Service
metadata:
  name: {{ include "oscar.name" . }}
  labels:
    {{- include "oscar.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    # TODO: replace with global service (check if exists, maybe)
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "oscar.selectorLabels" . | nindent 4 }}
