apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: s3-mounter
  name: s3-mounter
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels: 
      app: s3-mounter
  template:
    metadata:
      labels:
        app: s3-mounter
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
      - name: mounter 
        image: {{ .Values.image.repository }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["./goofys", "-f", "{{ .Values.bucketName }}", "{{ .Values.mountPath }}"]
        securityContext:
          privileged: true
        envFrom:
          - configMapRef:
              name: s3-config
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh","-c","umount -f", "{{ .Values.mountPath }}:shared"]
        volumeMounts:
        - name: mntdatas3
          mountPath: {{ .Values.mountPath }}:shared
      volumes:
      - name: mntdatas3
        hostPath:
          path: {{ .Values.hostPath }}