apiVersion: v1
kind: Service
metadata:
  name: {{ include "expedius.name" . }}
  labels:
    {{- include "expedius.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.global.services.expedius.port }}
      targetPort: {{ .Values.global.services.expedius.port }}
      protocol: TCP
  selector:
    {{- include "expedius.selectorLabels" . | nindent 4 }}
